site:

url: 
baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  projects_mlops:
    output: true
    23_fall:
      output: true
      group_7:
        output: true
  projects_toc_ml:
    output: true
    permalink: /semester/:slug
    order:
      - 23_spring.md
      - 22_fall.md
      - 22_summer.md
  projects_toc_mlops:
    output: true
    permalink: /semester/:slug
    order:
      - 23_fall.md
  abouts:
    output: true
    permalink: /about/:slug
  tas:
    output: true
    permalink: /tas/:slug
  ml:
    output: true
    permalink: /ml/:slug
  mlops:
    output: true
    permalink: /mlops/:slug    

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "projects_mlops"
    values:
      layout: "project"      
  -
    scope:
      path: ""
      type: "abouts"
    values:
      layout: "about"
  -
    scope:
      path: ""
      type: "projects_toc_ml"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "projects_toc_mlops"
    values:
      layout: "project"     

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"